name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Adjust to your default branch if not 'main'

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use the version supported by the app

    - name: Install Dependencies and Build
      run: |
        npm install
        npm run build

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        app_location: "/"              # Adjust to the correct folder
        output_location: "build"       # Adjust based on the build folder
